### ISSUE TITLE
Various issues/notes while changing to auto-generation

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1044]
- [ ] ~Improve whitespace of code generation, less diff to style fix~
- [x] Run proto generation in CI and style fix to check if there are no uncommitted changes  #1080
- [x] Change from `foo_async` to `subscribe_foo`. #1068
- [ ] ~Support for multiple cameras.~
- [x] Change `typedef mode_callback-t` ->`using ModeCallback` #1076
- [x] Fix remaining enums to `Camelcase`, e.g. `ConnectionResult`. #1075
- [x] Fix comments saying "wrapper around async" when there is no async. #1068
- [x] Clean up enum description (e.g. "Request succeeded"). #1080
- [x] Adapt examples. #1078 

FYI @JonasVautherin
